### ISSUE TITLE
bug: The spotlight effect on the title element looks very strange

### ISSUE THREAD

**Issue by Ray-D-Song** [nolebase/integrations#105]
<img width="908" alt="image" src="https://github.com/nolebase/integrations/assets/71577024/7248e78f-711f-43c7-86c7-be2f0e4cf2a4">

It appears that the top margin and divider line are included in the scope of the spotlight effect. Is this the expected behavior?

**Comment by LittleSound** [comment]
In fact, the CSS for these margins and dividers is indeed included in the header tag. So, separating them might be somewhat difficult.

**Comment by nekomeowww** [comment]
Thanks for the feedback!

This is an expected behavior due to the fact that the divider line is part of the header element.

Separate them apart is possible since spotlight involves with JavaScript code during runtime, but I personally think it is not worthy to do at this time while I do think this is a problem that VitePress team should address. On the other hand, implement such feature may also cause inconsistent behavior when the theme is customized, do we need to find a way to support majority of the themes or not?
