### ISSUE TITLE
How to use the `vitepress-plugin-og-image` pluggin ?

### ISSUE THREAD

**Issue by etienne-monier** [nolebase/integrations#244]
Hi,

I did not find in the docs how to use the `vitepress-plugin-og-image` pluggin.

I tried this in the `.vitepress/theme/config.mts`

```
import { buildEndGenerateOpenGraphImages } from "@nolebase/vitepress-plugin-og-image";

export default defineConfigWithTheme<ThemeConfig>({
  vite: {
    plugins: [
      buildEndGenerateOpenGraphImages({ baseUrl: "http://example.com" }),
    ],
  },
})
```

but this did not work due to type checks.

How can I test it?

**Comment by nekomeowww** [comment]
Sorry being later here. (I was in post-op recovery and haven't came up to communities to answer questions, hope you are not hurry)

In short, the reason why `buildEndGenerateOpenGraphImages` cannot put into `vite.plugins` is because the `buildEndGenerateOpenGraphImages` is not a Vite plugin but a VitePress [`buildEnd` plugin](https://vitepress.dev/reference/site-config#buildend) where the `buildEndGenerateOpenGraphImages` function will be invoked and called when VitePress finished to output the pages.

To use the `buildEndGenerateOpenGraphImages`, you will need two things:

1. specify the `baseUrl` (which you have done well, congrats!) for the actual deployed site.
2. by default, `vitepress-plugin-og-image`will try to search for `og-template.svg` under the [`/public` directory](https://vitepress.dev/guide/asset-handling#the-public-directory) for rendering and templating the `og` images. And it will use:
  - `{{category}}`
  - `{{siteName}}`
  - `{{siteDescription}}`
  - preview titles:
    - `{{line1}}`
    - `{{line2}}`
    - `{{line3}}`
as the templating variables. (I'm sorry for the bad design of this but I haven't came up any ideas to design this thing better and flexible enough for users & developers, PRs welcome, really :) )

So if you want to make up your own `og-template.svg`, you can use Figma, Adobe Illustrator to make something that contains the up above ones and throw it under `/public` directory and named as `og-template.svg` so it can process and render the images for you.
