### ISSUE TITLE
`@nolebase/markdown-it-unlazy-img` is not avalible

### ISSUE THREAD

**Issue by Kutius** [nolebase/integrations#305]
1. docs is wrong about package installation: `ni @nolebase/markdown-it-bi-unlazy-img -D`. It should be `@nolebase/markdown-it-unlazy-img`
2. After setting config, dev or build will be fail:
```ts
      md.use(UnlazyImages, {
        imgElementTag: 'NolebaseUnlazyImg',
      })
```

```
ENOENT: no such file or directory, open ''
Error: ENOENT: no such file or directory, open ''
    at readFileSync (node:fs:441:20)
```

**Comment by nekomeowww** [comment]
Sorry for the inconvenience, just a small docs issue, PR is welcome.

**Comment by Kutius** [comment]
> Sorry for the inconvenience, just a small docs issue, PR is welcome.

Yes It's just a negligible minor issue.
But after sucessful installation, I still can't run successfully, like the second problem above. Do you have some suggestions?

**Comment by nekomeowww** [comment]
Did you configured `@nolebase/vitepress-plugin-thumbnail-hash` too? It requires `@nolebase/vitepress-plugin-thumbnail-hash` to pre-process the images since `markdown-it` plugin doesn't allow async function invoking, which means I cannot perform thumbhash operations in `markdown-it`'s context (it should not be a async constructor too).

For more futuristic perspective, asking VitePress to switch to remark is more viable way, not sticking with md-it.

**Comment by Kutius** [comment]
> Did you configured `@nolebase/vitepress-plugin-thumbnail-hash` too? It requires `@nolebase/vitepress-plugin-thumbnail-hash` to pre-process the images since `markdown-it` plugin doesn't allow async function invoking, which means I cannot perform thumbhash operations in `markdown-it`'s context (it should not be a async constructor too).
> 
> For more futuristic perspective, asking VitePress to switch to remark is more viable way, not sticking with md-it.

Ok I get the key. Thank u!
