### ISSUE TITLE
bug(enhanced-readabilities): the spotlight is placed on a wrong position when i modify the zoom-scale of body

### ISSUE THREAD

**Issue by Glomzzz** [nolebase/integrations#329]
What caused the problem:
> style.css (which will be import in theme/index.ts
```css
body {
  zoom: 1.4;
}
```

You can see it here: https://glomzzz.com/docs/blogs/toughts/something-to-write-1

Perhaps there's a better way to make the body bigger, i thought.

Otherwise, perhaps making the "body-zoom-scale" customizable in enhanced-readabilities could solve it.

**Comment by nekomeowww** [comment]
Never heard of this property. I checked the browser native zooming functionalities, the Spotlight is working as intended, perhaps this is a browser side bug.

I use the commonly known rect properties to calculate the bounding box of the elements, which should never have problems (since how can I calculate the width, offset on my own if the bounding box is incorrect), if you have time to debug on your own, you may check on this https://github.com/nolebase/integrations/blob/99d79705d2993bcd34ce2588ed3b78199d1acdc8/packages/vitepress-plugin-enhanced-readabilities/src/client/components/SpotlightHoverBlock.vue#L98-L105 part of the code.

**Comment by Glomzzz** [comment]
I've figured out why this would lead a wrong offset of hover block.

> style.css (which will be import in theme/index.ts

```css
body {
  zoom: 1.4;
}
```

- The `zoom` property changes how elements are **visually scaled** but does not modify the actual DOM box model values or geometry used for layout calculations.
- `getBoundingClientRect()` reports the unscaled dimensions of the element based on the DOM box model, which wasn't zoomed by css.

Given I just wanted to make those texts bigger, this is a incorrect way to do it.
Instead, I try to make only the texts bigger by modifying `font-size`, which works perfectly.

```css
.Layout {
  font-size: 140%;
}
```

( So currently, no code needs to be changed

**Comment by nekomeowww** [comment]
Nice investigation, just learned it! Thank you for the feedbacks about your conclusions.
