### ISSUE TITLE
documentation: missing configuration of `vue` when using `unlazy-img` which leads built docs with 404 of images

### ISSUE THREAD

**Issue by Alaye-Dong** [nolebase/integrations#363]
I have read the documentation and configured `@nolebase/vitepress-plugin-thumbnail-hash` and `@nolebase/markdown-it-unlazy-img`.

After running the `docs:dev` command, everything works fine in the development server—both thumbnail-hash and unlazy-img functions as expected. 🐞However, after building with `docs:preview`, the images on the generated site continuously display as blurred thumbnails and fail to load the original images. The developer tools indicate a 404 error when trying to access the images.

![image](https://github.com/user-attachments/assets/b4111a84-3064-4105-8542-d29ab74e640d)

I have uploaded the code to the repository branch [dubug-thumbnail-unlazy](https://github.com/Alaye-Dong/JXUT-BST-IO-VitePress/tree/dubug-thumbnail-unlazy)

Any insights or suggestions to resolve this issue would be greatly appreciated. Thank you for your help and support in advance!😊

**Comment by nekomeowww** [comment]
This part of config is missing:

https://github.com/nolebase/integrations/blob/588a44364596fa1db68246afda92793e605722cd/docs/.vitepress/config.ts#L298-L309

I think the documentation should correctly state this configuration and explain everything out. Since you are here already to help Nolebase community, you're welcome to open up a dedicated PR to add this part of the configuration into the documentation.

**Comment by nekomeowww** [comment]
Close as docs has been updated.
