### ISSUE TITLE
please improve the documentation

### ISSUE THREAD

**Issue by zjcscut** [nolebase/integrations#63]
Please improve the documentation of the list of integrations: 
- Elements Transformation (for markdown-it)
- Inline Link Previewing (for VitePress)
- Changelog & File history (for VitePress)

I want to try these integrations but found no docs to read😂😂

**Comment by nekomeowww** [comment]
I'm so sorry!

## Element Transformation

This markdown-it plugin is intended to be used as replacing all the `<a>` elements to `<InlineLinkPreview>` components.

This is the living example code where we use it as references:

https://github.com/nolebase/integrations/blob/08c4e47f43f4678e2138401f8b62a1966a48b6ba/docs/.vitepress/config.ts#L147-L169

However, such useage is a temporary workaround due to the fact that I haven't refactor `Inline Link Previewing` plugin to listen the mouse hovering event of all the `<a>` elements as singleton instance across all pages for both better accessibilities and compatibilities (since it replaces all the `<a>` elements and may break the markdown processing pipelines for advanced users).

## Inline Link Previewing

This vitepress plugin is an implementation of Obsidian's link previewing functionalities.

To use it, you need to combine with `Element Transformation`:

https://github.com/nolebase/integrations/blob/08c4e47f43f4678e2138401f8b62a1966a48b6ba/docs/.vitepress/config.ts#L147-L169

And use the components as follows:

https://github.com/nolebase/integrations/blob/08c4e47f43f4678e2138401f8b62a1966a48b6ba/docs/.vitepress/theme/index.ts#L57

Don't forget to include the stylesheets as well:

https://github.com/nolebase/integrations/blob/08c4e47f43f4678e2138401f8b62a1966a48b6ba/docs/.vitepress/theme/index.ts#L28

## Changelog & File history

This vitepress plugin read the git log as file history and renders through components with both `Contributors` section and `Changelog` section available in Markdown file.

The reason why we haven't made a documentation for it is because we have another pending issue #45 to improve the overall performance and user experience, we might change the API in the nearby future when refactoring.

This is roughly the most complex one to configure with.

First, you need a `vite.config.ts` or `vite` option in `config` property of `vitepres`, and then configure these two Vite plugins to read, prepare the git log data for components to render with, transform the Markdown file with the two new additional sections:

https://github.com/nolebase/integrations/blob/08c4e47f43f4678e2138401f8b62a1966a48b6ba/docs/vite.config.ts#L11-L35

And use the components as follows:

https://github.com/nolebase/integrations/blob/08c4e47f43f4678e2138401f8b62a1966a48b6ba/docs/.vitepress/theme/index.ts#L69-L84

Don't forget to include the stylesheets as well:

https://github.com/nolebase/integrations/blob/08c4e47f43f4678e2138401f8b62a1966a48b6ba/docs/.vitepress/theme/index.ts#L30

**Comment by nekomeowww** [comment]
Sorry about the lack of documentations of our plugins. Feel free to ask any questions here and even provide us feedback about the not-well-designed plugins.

You are welcome to contribute documentations about these plugins if you want (either one language you comfort with)

**Comment by zjcscut** [comment]
Thx. I will try it latter
